name: Test
on:
  push:
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install all dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: yarn test